insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(1,'Crunch',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(2,'Sit-Up',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(3,'Relevés de Jambes',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(4,'Relevé de jambes sur plan incliné',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(5,'Relevé de buste sur banc incliné',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(6,'Relevé de bassin sur plan incliné',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(7,'Crunch avec Rotation',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(8,'Relevé de jambes en suspension',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(9,'Torsion de Bassin couché',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(10,'Flexions Latérales',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(11,'Pompes',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(12,'Écarté Couché Incliné',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(13,'Développé Couché',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(14,'Écarté Couché',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(15,'Pec Deck',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(16,'Développé Décliné',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(17,'Dips',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(18,'Poulie vis-à-vie',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(19,'Pull Over',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(20,'Développé Nuque',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(21,'Développé Devant',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(22,'Développé Haltère',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(23,'Rowing Menton',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(24,'Élévations Latérales',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(25,'Oiseau Banc Incliné',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(26,'Curl Barre',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(27,'Curl Haltère',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(28,'Curl Pupitre',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(29,'Curl Concentration',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(30,'Barre Front',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(31,'Extensions au dessus de la tete',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(32,'Kick Back',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(33,'Poulie Haute',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(34,'Développés et Dips',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(35,'Tractions Barre Fixe',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(36,'Tirage Poitrine',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(37,'Tirage Nuque',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(38,'Tirage prise serrée',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(39,'Rowing Barre',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(40,'Rowing un bras',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(41,'Rowing barre T',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(42,'Tirage sol',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(43,'Haussement d''épaules',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(44,'Extensions au Banc',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(45,'Good-morning',0,'false',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(46,'Squat',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(47,'Squat une jambe',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(48,'Presse à cuisses',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(49,'Hack Squat',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(50,'Leg Extension',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(51,'Sissy Squat',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(52,'Fentes',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(53,'Leg Curl Arrière',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(54,'Soulevé de Terre',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(55,'Soulevé de Terre roumain',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(56,'Soulevé de Terre jambes tendues',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(57,'Mollets Assis',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(58,'Mollets Debout',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(59,'Mollets à la Presse',0,'true',0,'');
insert into exercise ("id_exercise","name","type","weight","difficulty","description") values(60,'Mollets Donkey',0,'false',0,'');

insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(1,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(2,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(3,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(4,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(5,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(6,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(7,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(8,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(9,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(11,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(10,1);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(12,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(13,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(14,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(15,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(16,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(17,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(18,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(19,12);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(20,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(21,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(22,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(25,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(23,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(24,7);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(26,3);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(27,3);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(28,3);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(29,3);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(30,14);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(31,14);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(32,14);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(33,14);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(34,14);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(35,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(36,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(37,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(39,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(40,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(38,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(41,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(42,6);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(43,13);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(44,9);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(46,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(47,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(48,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(49,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(50,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(51,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(52,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(53,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(54,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(55,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(45,9);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(56,5);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(57,10);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(58,10);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(59,10);
insert into exercise_muscle_group ("id_exercise","id_muscle_group") values(60,10);
